services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - dream
    environment:
      - TZ=Asia/Seoul

networks:
  dream:
    external: true